### ISSUE TITLE
Docs causing `hexo generate` errors

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#327]
```js
Unhandled rejection TypeError: /opt/aframe-site/themes/aframe/layout/docs.ejs:15
    13|         <% docs_versions(config.aframe_version).map(function (version) { %>
    14|           <option <%- activeVersion === version && 'selected' %>
 >> 15|                   data-href="<%- docs_root_path(site.pages, version) %>">
    16|             <%- version %>
    17|           </option>
    18|         <% }); %>

Cannot read property 'path' of undefined
    at Object.<anonymous> (/opt/aframe-site/scripts/helpers.js:242:20)
    at Object.wrapper [as docs_root_path] (/opt/aframe-site/node_modules/hexo/node_modules/lodash/lodash.js:4762:19)
    at eval (eval at <anonymous> (/opt/aframe-site/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:808)
    at Array.map (native)
    at eval (eval at <anonymous> (/opt/aframe-site/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:628)
    at eval (eval at <anonymous> (/opt/aframe-site/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:37:451)
    at /opt/aframe-site/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/opt/aframe-site/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/opt/aframe-site/node_modules/hexo/lib/theme/view.js:29:15)
    at /opt/aframe-site/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/opt/aframe-site/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/aframe-site/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/aframe-site/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:726:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

Unhandled rejection TypeError: /opt/aframe-site/themes/aframe/layout/docs.ejs:15
    13|         <% docs_versions(config.aframe_version).map(function (version) { %>
    14|           <option <%- activeVersion === version && 'selected' %>
 >> 15|                   data-href="<%- docs_root_path(site.pages, version) %>">
    16|             <%- version %>
    17|           </option>
    18|         <% }); %>
```

**Comment by cvan** [comment]
Fixed by `npm install` 👍
