### ISSUE TITLE
Cannot read property 'path' of undefined - Hexo Start Up

### ISSUE THREAD

**Issue by shaundunne** [aframevr/aframe-site#409]
Gone through the setup to get up and running, but when trying to access the page I get this error.

```bash
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /Users/Shaun/code/os/aframe-site/themes/aframe/layout/index.ejs:15
    13|     <ul class="menu">
    14|       <li class="menu-item">
 >> 15|         <a href="<%- url_for(docs_root_path(site.pages, config.aframe_version)) %>">Docs</a>
    16|       </li>
    17|       <li class="menu-item">
    18|         <a href="<%- url_for('faq/') %>">FAQ</a>

Cannot read property 'path' of undefined
    at Object.<anonymous> (/Users/Shaun/code/os/aframe-site/scripts/helpers.js:247:20)
    at Object.wrapper [as docs_root_path] (/Users/Shaun/code/os/aframe-site/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at exports.compile (/Users/Shaun/code/os/aframe-site/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:576)
    at eval (eval at exports.compile (/Users/Shaun/code/os/aframe-site/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1521)
    at /Users/Shaun/code/os/aframe-site/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled (/Users/Shaun/code/os/aframe-site/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/Shaun/code/os/aframe-site/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/Shaun/code/os/aframe-site/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/Shaun/code/os/aframe-site/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/Shaun/code/os/aframe-site/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/Shaun/code/os/aframe-site/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by dmarcos** [comment]
Are you on Windows?

**Comment by shaundunne** [comment]
No. Mac - Sierra. Node version 7.2.1 (also tried in 5.4.1)

**Comment by ngokevin** [comment]
Did you install the docs? ```npm run installdocs```

**Comment by shaundunne** [comment]
Ah, I ran it together with the other commands (as it was in the docs)

`npm install && npm installdocs && npm start`

but seems that running it separately has got it working! Ah, npm.

Thanks.

**Comment by ngokevin** [comment]
I've made it part of the postinstall process again, so hopefully, it should work next time on a fresh clone.

**Comment by stepan-techs** [comment]
I installed it in different ways. Multiple times.
And getting this error anyway
Unhandled rejection TypeError: F:\VR\aframe-site\themes\aframe\layout\index.ejs:15
    13|     <ul class="menu">
...
Cannot read properties of undefined (reading 'path')
    at Object.<anonymous> (F:\VR\aframe-site\scripts\helpers.js:248:21)
...

**Comment by dmarcos** [comment]
@stepan-techs what are you trying to accomplish? Just to make sure. Are you trying to work on the A-Frame website?
What versions of node / npm are you using? `npm --version, node --version`
